language: ruby
rvm:
  - 2.2.2
before_install: gem install bundler -v 1.11.2
install: bundle install --jobs=3 --retry=3 --deployment --without development
services:
  - mysql
before_script:
  - mysql -e 'create database myapp_test;'
  - cp config/database.travis.yml config/database.yml
  - cp config/secrets.travis.yml config/secrets.yml
script:  
  - RAILS_ENV=test bundle exec rake db:migrate
  - RAILS_ENV=test bundle exec rspec spec/
  - RAILS_ENV=test bundle exec rspec cucumber