site_url:
  name: Site Url (avec un "/" à la fin)
  default: http://localhost:3000/
  type: string

use_platal:
  name: Activer les recherches dans platal
  default: true
  type: boolean

use_helpdesk_chat:
  name: Activer la messagerie instantannée de support
  default: true
  type: boolean

anonymous_helpdesk_chat:
  name: Activer la messagerie instantannée de support même si l'utilisateur n'est pas connecté
  default: true
  type: boolean

legacy_auth_enabled:
  name: "Afficher la page d'authentification interne aux utilisateur"
  default: true
  type: boolean

url_site_soce_admin_user:
  name: Url admin des user du site soce
  default: https://www.arts-et-metiers.asso.fr/index.php/adminMembres/index/id_user