# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#

# default: &default
#   adapter: sqlite3
#   pool: 5
#   timeout: 5000

test:
  adapter: mysql2
  database: myapp_test
  username: travis
  encoding: utf8

soce_test:
  adapter: mysql2
  database: soce_test # defined in db/soce_test_db_schema.sql
  username: travis
  encoding: utf8