CREATE DATABASE `soce_test` /*!40100 DEFAULT CHARACTER SET utf8 */;

USE `soce_test`;

CREATE TABLE `users` (
  `id_user` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `id_user_chksum` varchar(1) DEFAULT NULL,
  `id_civilite` int(10) unsigned DEFAULT NULL,
  `id_type_societaire` int(10) unsigned DEFAULT NULL,
  `id_conjoint` int(10) unsigned DEFAULT NULL,
  `nom` varchar(100) DEFAULT NULL,
  `prenom` varchar(100) DEFAULT NULL,
  `nom_jeune_fille` varchar(100) DEFAULT NULL,
  `parente` int(10) unsigned DEFAULT NULL,
  `date_naissance` date DEFAULT NULL,
  `login` varchar(100) DEFAULT NULL,
  `pass` varchar(100) DEFAULT NULL,
  `pass_crypt` varchar(255) DEFAULT NULL,
  `email` varchar(255) DEFAULT NULL,
  `email_valide` int(1) DEFAULT '0',
  `email_secondaire` varchar(255) DEFAULT NULL,
  `id_ensam` varchar(30) DEFAULT NULL,
  `promo1` int(4) DEFAULT NULL,
  `promo2` int(4) DEFAULT NULL,
  `promo3` int(4) DEFAULT NULL,
  `centre1` int(10) unsigned DEFAULT NULL,
  `centre2` int(10) unsigned DEFAULT NULL,
  `centre3` int(10) unsigned DEFAULT NULL,
  `filiere1` int(10) unsigned DEFAULT NULL,
  `filiere2` int(10) unsigned DEFAULT NULL,
  `filiere3` int(10) unsigned DEFAULT NULL,
  `id_membre_associe` int(10) unsigned DEFAULT NULL,
  `id_type_associe` int(10) unsigned DEFAULT NULL,
  `tel_mobile` varchar(40) DEFAULT NULL,
  `date_creation` datetime DEFAULT NULL,
  `date_maj` datetime DEFAULT NULL,
  `sexe` varchar(1) DEFAULT NULL,
  `figuration_annuaire` int(1) unsigned DEFAULT NULL,
  `figuration_annuaire_adr_perso` int(1) NOT NULL DEFAULT '1',
  `figuration_annuaire_adr_pro` int(1) NOT NULL DEFAULT '1',
  `figuration_email` int(1) unsigned DEFAULT NULL,
  `figuration_externe` int(1) unsigned DEFAULT NULL,
  `figuration_web` int(10) unsigned DEFAULT NULL,
  `figuration_web_adr_perso` int(1) NOT NULL DEFAULT '1' COMMENT '1 : info affichée',
  `figuration_web_adr_pro` int(1) NOT NULL DEFAULT '1' COMMENT '1 : info affichée',
  `date_sortie` date DEFAULT NULL,
  `date_adhesion` date DEFAULT NULL,
  `date_readhesion` date DEFAULT NULL,
  `date_demission` date DEFAULT NULL,
  `date_deces` date DEFAULT NULL,
  `date_radiation` date DEFAULT NULL,
  `date_relance_cotis` date DEFAULT NULL,
  `date_ouverture_img_relance_cotis` datetime DEFAULT NULL,
  `type_reception_annuaire` int(1) unsigned DEFAULT NULL,
  `modif` text,
  `date_validation` date DEFAULT NULL,
  `adresseip` varchar(20) DEFAULT NULL,
  `photo` varchar(255) DEFAULT NULL,
  `cot_ar0` int(11) DEFAULT NULL,
  `cot_ar1` int(11) DEFAULT NULL,
  `cot_ar2` int(11) DEFAULT NULL,
  `cot_ar3` int(11) DEFAULT NULL,
  `nb_cot` int(11) DEFAULT NULL,
  `type_abt` int(11) DEFAULT NULL,
  `fin_abt` date DEFAULT NULL,
  `nb_abt` int(11) DEFAULT NULL,
  `date_fin_amm_web` date DEFAULT NULL,
  `relance_amm` int(1) NOT NULL DEFAULT '1',
  `annuaire_encours` int(11) DEFAULT NULL,
  `surnom` varchar(200) DEFAULT NULL,
  `buque_zaloeil` varchar(200) DEFAULT NULL,
  `famille1` varchar(20) DEFAULT NULL,
  `famille2` varchar(20) DEFAULT NULL,
  `famille3` varchar(20) DEFAULT NULL,
  `famille_zaloeil` varchar(20) DEFAULT NULL,
  `id_users_parente` int(11) DEFAULT NULL,
  `date_radiation2` date DEFAULT NULL,
  `premiere_connexion` int(11) DEFAULT NULL,
  `date_maj_paiement` date DEFAULT NULL,
  `dernier_annee_cotiz_associe` date DEFAULT NULL,
  `dernier_annee_cotiz_cg` date DEFAULT NULL,
  `total_arriere` float DEFAULT NULL,
  `date_declaration_deces` date DEFAULT NULL,
  `date_dernier_changement_mdp` date DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `trans_pay_siam` tinyint(4) NOT NULL,
  `annuaire_expedie` tinyint(4) NOT NULL DEFAULT '0',
  `id_filiere` int(11) DEFAULT NULL,
  `id_sous_filiere` int(11) DEFAULT NULL,
  `annee_filiere` mediumint(9) DEFAULT NULL,
  `societe_externe` varchar(255) DEFAULT NULL,
  `donnees_pro_paristech` tinyint(4) NOT NULL DEFAULT '0',
  `donnees_perso_paristech` tinyint(4) NOT NULL DEFAULT '0',
  `abonnement_veuve` tinyint(4) DEFAULT NULL COMMENT '0:pas d''abo, 1:premier courrier ok, 2:deuxieme courier ok',
  `date_originale_fin_abo_amm` date DEFAULT NULL COMMENT 'date présente en cas de prolongation promotionnelle',
  `fonction_externe` varchar(255) DEFAULT NULL,
  `promo_externe` varchar(45) DEFAULT NULL,
  `ecole_externe` varchar(45) DEFAULT NULL,
  `carte_de_membre_editee` tinyint(4) DEFAULT NULL,
  `adhesion_recue` tinyint(4) NOT NULL DEFAULT '0',
  `adhesion_avis` varchar(1) DEFAULT NULL,
  `id_centre_dsc` int(11) DEFAULT NULL COMMENT 'id du centre si responsabilite DSC',
  `date_passage_membre_a_vie` date DEFAULT NULL,
  `forlife_gadz_org` varchar(100) DEFAULT NULL,
  `bestalias_gadz_org` varchar(150) DEFAULT NULL,
  `autoriser_diffusion_vers_gadz_org` tinyint(4) DEFAULT NULL,
  `autoriser_diffusion_vers_cge` int(1) NOT NULL DEFAULT '1',
  `rapel_imelavi` tinyint(2) DEFAULT NULL,
  `societe_manif_externe` varchar(255) DEFAULT NULL,
  `cursus_manif_externe` varchar(255) DEFAULT NULL,
  `motif_exoneration` varchar(255) DEFAULT NULL,
  `bloquer_transfert_isf` tinyint(4) DEFAULT NULL,
  `autoriser_diffusion_ecole` tinyint(4) NOT NULL DEFAULT '1',
  `bloquer_com_email` tinyint(1) NOT NULL DEFAULT '0',
  `compte_desactive` tinyint(4) NOT NULL DEFAULT '0',
  `date_rappel_maj_coordonnees` date DEFAULT NULL,
  `date_limite_bloquage_relance_cotiz` date DEFAULT NULL,
  `date_effacement_si_compte_temporaire` date DEFAULT NULL,
  `hruid` varchar(255) DEFAULT NULL,
  `linkedin` varchar(100) DEFAULT NULL,
  `id_bande` int(11) DEFAULT NULL,
  `a_propos_de_moi` text,
  `figuration_annuaire_publique` tinyint(4) NOT NULL DEFAULT '0',
  `is_gadzart` tinyint(4) NOT NULL DEFAULT '0',
  `uuid` varchar(100) NOT NULL,
  `migration_platal` tinyint(4) NOT NULL DEFAULT '0',
  `date_migration_platal` date NOT NULL,
  PRIMARY KEY (`id_user`),
  UNIQUE KEY `idx_users_hruid` (`hruid`),
  KEY `promo1` (`promo1`),
  KEY `promo2` (`promo2`),
  KEY `promo3` (`promo3`),
  KEY `centre1` (`centre1`),
  KEY `centre2` (`centre2`),
  KEY `centre3` (`centre3`),
  KEY `filiere1` (`filiere1`),
  KEY `filiere2` (`filiere2`),
  KEY `filiere3` (`filiere3`),
  KEY `id_type_societaire` (`id_type_societaire`),
  KEY `id_civilite` (`id_civilite`),
  KEY `email` (`email`),
  KEY `compte_desactive` (`compte_desactive`),
  KEY `hruid` (`hruid`),
  KEY `uuid` (`uuid`)
) ENGINE=MyISAM AUTO_INCREMENT=309671 DEFAULT CHARSET=utf8;
